name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0，留空则使用时间戳)'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  # 创建版本号
  increment-version:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'release'))
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set version
        id: set-version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            # 使用用户输入的版本号
            NEW_VERSION="${{ github.event.inputs.version }}"
          else
            # 使用时间戳作为版本号
            NEW_VERSION="v$(date +'%Y.%m.%d-%H%M')"
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-version.outputs.NEW_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ steps.set-version.outputs.NEW_VERSION }}"
          body: "Release ${{ steps.set-version.outputs.NEW_VERSION }}"
          prerelease: false
          draft: false


  build-and-upload:
    name: Build and Upload
    needs: increment-version
    strategy:
      matrix:
        node: [lts/*]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Build
        env:
          os: win
        run: |
          npm run install-all
          npm run build
          npm run electron:build:${{ env.os }}

      - name: Rename files
        run: |
          mv "./dist_electron/MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe" "./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe"
          mv "./dist_electron/MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap" "./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap"
          mv "./dist_electron/latest.yml" "./latest.yml"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.increment-version.outputs.version }}
          files: |
            ./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe
            ./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap
            ./latest.yml
